CREATE OR REPLACE TABLE DATAMART.DAILY_GROSS_REVENUE AS (
WITH T1 as (
    SELECT DATE_ORDER.ORDER_DATE, DETAIL.ORDER_ID, DETAIL.QUANTITY, DETAIL.DISCOUNT, DETAIL.UNIT_PRICE
    FROM PUBLIC.ORDER_DETAILS AS DETAIL
    LEFT JOIN PUBLIC.ORDERS AS DATE_ORDER
    ON DETAIL.ORDER_ID = DATE_ORDER.ORDER_ID
    WHERE DATE_ORDER.ORDER_DATE >='2023-01-01'
)
SELECT T1.ORDER_DATE,
    SUM(T1.QUANTITY*(T1.UNIT_PRICE -(T1.DISCOUNT * T1.UNIT_PRICE))) AS GROSS_REVENUE
FROM T1
GROUP BY 1
ORDER BY 1
);