CREATE OR REPLACE TABLE DATAMART.MONTHLY_ORDERS_CATAGORIES AS(
    WITH T1 as (
        SELECT DATE_ORDER.ORDER_DATE, DETAIL.PRODUCT_ID, DETAIL.QUANTITY
        FROM PUBLIC.ORDER_DETAILS AS DETAIL
        LEFT JOIN PUBLIC.ORDERS AS DATE_ORDER
        ON DETAIL.ORDER_ID = DATE_ORDER.ORDER_ID
        WHERE DATE_ORDER.ORDER_DATE >='2023-01-01'
    ),
    T2 AS (
        SELECT T1.ORDER_DATE,
            T1.PRODUCT_ID,
            SUM(T1.QUANTITY) AS QUANTITY
        FROM T1
        GROUP BY 1,2
    ),
    T3 AS (
        SELECT date_trunc('MONTH',T2.ORDER_DATE) AS DATE,
            T2.PRODUCT_ID,
            SUM(T2.QUANTITY) AS QUANTITY
        FROM T2
        GROUP BY 1, 2
    ),
    T4 AS (
        SELECT T3.DATE, 
            PRODUCT.CATEGORY_ID, 
            SUM(T3.QUANTITY) AS QUANTITY
        FROM T3
        LEFT JOIN PUBLIC.PRODUCTS AS PRODUCT
        ON PRODUCT.PRODUCT_ID = T3.PRODUCT_ID
        GROUP BY 1, 2
        ORDER BY 1
    )
    SELECT T4.DATE,
        CAT.CATEGORY_NAME,
        T4.QUANTITY
    FROM T4
    LEFT JOIN PUBLIC.CATEGORIES AS CAT
    ON CAT.CATEGORY_ID = T4.CATEGORY_ID
    ORDER BY 1
);