
--ctas gross revenue daily 
-- USE FINAL_PROJECT_FUAD;
-- CREATE TABLE GROSS_REVENUE 
--     AS SELECT a.quantity,
--     b.PRODUCT_NAME, 
--     a.product_id,
--     a.discount,
--     a.unit_price,
--     a.order_id,
--     c.order_date 
--     FROM PUBLIC.ORDER_DETAILS a 
-- INNER JOIN PUBLIC.PRODUCTS b
--     ON a.PRODUCT_ID=b.PRODUCT_ID
-- INNER JOIN PUBLIC.ORDERS C 
--     ON a.order_id=c.order_id;


--GROSS REVENUE DAILY 
USE FINAL_PROJECT_FUAD;
CREATE OR REPLACE TABLE GROSS_REVENUE_DAILY AS 
SELECT DATE(ORDER_DATE) AS "ORDER DATE",
    SUM((UNIT_PRICE * QUANTITY) - (UNIT_PRICE * QUANTITY * DISCOUNT)) AS "GROSS REVENUE DAILY"
FROM PUBLIC.GROSS_REVENUE
GROUP BY DATE(ORDER_DATE)
ORDER BY DATE(ORDER_DATE);

SELECT * FROM PUBLIC.GROSS_REVENUE ;


--GROSS REVENUE PER PRODUCT MONTH 
USE FINAL_PROJECT_FUAD;
CREATE OR REPLACE TABLE GROSS_REVENUE_MONTH AS
SELECT
    CASE
        WHEN EXTRACT(MONTH FROM ORDER_DATE) = 1 THEN 'Januari'
        WHEN EXTRACT(MONTH FROM ORDER_DATE) = 2 THEN 'Februari'
        WHEN EXTRACT(MONTH FROM ORDER_DATE) = 3 THEN 'Maret'
        WHEN EXTRACT(MONTH FROM ORDER_DATE) = 4 THEN 'April'
        WHEN EXTRACT(MONTH FROM ORDER_DATE) = 5 THEN 'Mei'
        WHEN EXTRACT(MONTH FROM ORDER_DATE) = 6 THEN 'Juni'
        WHEN EXTRACT(MONTH FROM ORDER_DATE) = 7 THEN 'Juli'
        WHEN EXTRACT(MONTH FROM ORDER_DATE) = 8 THEN 'Agustus'
        WHEN EXTRACT(MONTH FROM ORDER_DATE) = 9 THEN 'September'
        WHEN EXTRACT(MONTH FROM ORDER_DATE) = 10 THEN 'Oktober'
        WHEN EXTRACT(MONTH FROM ORDER_DATE) = 11 THEN 'November'
        WHEN EXTRACT(MONTH FROM ORDER_DATE) = 12 THEN 'Desember'
    END AS "MONTHLY",
    PRODUCT_NAME,
    EXTRACT(MONTH FROM ORDER_DATE) AS "MONTH",
    SUM(UNIT_PRICE * QUANTITY * (1 - DISCOUNT)) AS GROSS_REVENUE
FROM
    PUBLIC.GROSS_REVENUE
GROUP BY
    PRODUCT_NAME,
    EXTRACT(MONTH FROM ORDER_DATE)
ORDER BY
    PRODUCT_NAME,
    "MONTHLY";

--TOTAL PEMBELIAN PRODUCT PERBULAN 
USE FINAL_PROJECT_FUAD;
CREATE OR REPLACE TABLE PURCHASES_MONTHLY_PRODUCT
AS SELECT 
    EXTRACT(MONTH FROM O.ORDER_DATE) AS Month,
    p.PRODUCT_ID,
    p.PRODUCT_NAME,
    (QUANTITY * UNIT_PRICE * (1 - DISCOUNT)) AS TOTAL_PURCHASES
FROM
    ORDERS o
    INNER JOIN ORDER_DETAILS od ON o.ORDER_ID = od.ORDER_ID
    INNER JOIN PRODUCTS p ON od.PRODUCT_ID = p.PRODUCT_ID
GROUP BY
    EXTRACT(MONTH FROM o.ORDER_DATE),
    p.PRODUCT_ID,
    p.PRODUCT_NAME
ORDER BY
    Month ASC,
    p.PRODUCT_ID ASC;
--TOP 10 PEMBELIAN PRODUCT PERBULAN
SELECT PRODUCT_ID,PRODUCT_NAME,TOTAL_PURCHASES,
CASE
        WHEN MONTH = 1 THEN 'Januari'
        WHEN MONTH = 2 THEN 'Februari'
        WHEN MONTH = 3 THEN 'Maret'
        WHEN MONTH = 4 THEN 'April'
        WHEN MONTH = 5 THEN 'Mei'
        WHEN MONTH = 6 THEN 'Juni'
        WHEN MONTH = 7 THEN 'Juli'
        WHEN MONTH = 8 THEN 'Agustus'
        WHEN MONTH = 9 THEN 'September'
        WHEN MONTH = 10 THEN 'Oktober'
        WHEN MONTH = 11 THEN 'November'
        WHEN MONTH = 12 THEN 'Desember'
    END AS "MONTHLY"
FROM PUBLIC.PURCHASES_MONTHLY
ORDER BY TOTAL_PURCHASES DESC
LIMIT 10;

--TOTAL PEMBELIAN PER KATEGORI PRODUK PER BULAN 
USE FINAL_PROJECT_FUAD;
CREATE OR REPLACE TABLE PURCHASES_CATEGORY_PRODUCT_MONTHLY AS
SELECT
        CASE
        WHEN EXTRACT(MONTH FROM ORDER_DATE) = 1 THEN 'Januari'
        WHEN EXTRACT(MONTH FROM ORDER_DATE) = 2 THEN 'Februari'
        WHEN EXTRACT(MONTH FROM ORDER_DATE) = 3 THEN 'Maret'
        WHEN EXTRACT(MONTH FROM ORDER_DATE) = 4 THEN 'April'
        WHEN EXTRACT(MONTH FROM ORDER_DATE) = 5 THEN 'Mei'
        WHEN EXTRACT(MONTH FROM ORDER_DATE) = 6 THEN 'Juni'
        WHEN EXTRACT(MONTH FROM ORDER_DATE) = 7 THEN 'Juli'
        WHEN EXTRACT(MONTH FROM ORDER_DATE) = 8 THEN 'Agustus'
        WHEN EXTRACT(MONTH FROM ORDER_DATE) = 9 THEN 'September'
        WHEN EXTRACT(MONTH FROM ORDER_DATE) = 10 THEN 'Oktober'
        WHEN EXTRACT(MONTH FROM ORDER_DATE) = 11 THEN 'November'
        WHEN EXTRACT(MONTH FROM ORDER_DATE) = 12 THEN 'Desember'
    END AS "MONTHLY",
    c.category_id,
    c.category_name,
    SUM(od.UNIT_PRICE * od.QUANTITY * (1 - od.DISCOUNT)) AS Total_Purchases
FROM
    ORDER_DETAILS od
    INNER JOIN PRODUCTS p ON od.product_id = p.product_id
    INNER JOIN CATEGORIES c ON p.category_id = c.category_id
    INNER JOIN ORDERS o ON od.order_id = o.order_id
GROUP BY
    EXTRACT(MONTH FROM o.ORDER_DATE),
    c.category_id,
    c.category_name;

--TOP 10 PEMBELIAN PER KATEGORI PRODUK BULANAN 
SELECT * FROM PUBLIC.PURCHASES_CATEGORY_PRODUCT_MONTHLY
ORDER BY TOTAL_PURCHASES DESC
LIMIT 10;


--JUMLAH TOTAL PEMBELIAN PER NEGARA PERBULAN 
CREATE OR REPLACE TABLE PURCHASES_MONTHLY_COUNTRY AS SELECT
CASE
        WHEN EXTRACT(MONTH FROM ORDER_DATE) = 1 THEN 'Januari'
        WHEN EXTRACT(MONTH FROM ORDER_DATE) = 2 THEN 'Februari'
        WHEN EXTRACT(MONTH FROM ORDER_DATE) = 3 THEN 'Maret'
        WHEN EXTRACT(MONTH FROM ORDER_DATE) = 4 THEN 'April'
        WHEN EXTRACT(MONTH FROM ORDER_DATE) = 5 THEN 'Mei'
        WHEN EXTRACT(MONTH FROM ORDER_DATE) = 6 THEN 'Juni'
        WHEN EXTRACT(MONTH FROM ORDER_DATE) = 7 THEN 'Juli'
        WHEN EXTRACT(MONTH FROM ORDER_DATE) = 8 THEN 'Agustus'
        WHEN EXTRACT(MONTH FROM ORDER_DATE) = 9 THEN 'September'
        WHEN EXTRACT(MONTH FROM ORDER_DATE) = 10 THEN 'Oktober'
        WHEN EXTRACT(MONTH FROM ORDER_DATE) = 11 THEN 'November'
        WHEN EXTRACT(MONTH FROM ORDER_DATE) = 12 THEN 'Desember'
    END AS "MONTHLY"
or.SHIP_COUNTRY AS COUNTRY
SUM(od.UNIT_PRICE * od.QUANTITY * (1 - od.DISCOUNT)) AS TOTAL_PURCHASES
FROM 
    order_details as od 
    INNER JOIN orders as or
ON od.ORDER_ID=or.ORDER_ID
    GROUP BY 
EXTRACT(MONTH FROM or.ORDER_DATE),
or.SHIP_COUNTRY;